gantt
    title Sistema de Gestion de Seguros VILLALOBOS - v1.0 Concepto inicial
    dateFormat  YYYY-MM-DD

    section Fases del Proyecto
    Analisis y Requerimientos       :fase1, 2025-08-01, 30d
    Diseño del Sistema              :fase2, after fase1, 30d
    Desarrollo                      :fase3, after fase2, 60d
    Testing                         :fase4, after fase3, 30d
    Despliegue                      :fase5, after fase4, 15d
